version: '3.8'
services:
  causal_explorer:
    image: cdoswald/personal:cs590
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/cdo19/cs590/workspace:/workspace
        
    
